packages:
  - "apps/*"
  - "packages/*"
overrides:
  postcss: ">=8.5.10"
  multer: "2.2.0"
  js-yaml: ">=4.2.0"
allowBuilds:
  "@scarf/scarf": false
  "@swc/core": true
  argon2: true
  bcrypt: false
  esbuild: true
  sharp: true
  unrs-resolver: true
