import * as Joi from 'joi';

export const environmentValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'test', 'production')
    .default('development'),
  PORT: Joi.number().default(4000),
  FRONTEND_URL: Joi.string().uri().default('http://localhost:3000'),
  DATABASE_URL: Joi.string().optional().allow(''),
  DATABASE_SSL: Joi.string().valid('true', 'false').default('false'),
  DATABASE_HOST: Joi.string().default('localhost'),
  DATABASE_PORT: Joi.number().default(5432),
  DATABASE_USER: Joi.string().default('mrh_admin'),
  DATABASE_PASSWORD: Joi.string().default('mrh_password_dev'),
  DATABASE_NAME: Joi.string().default('mrh_academy_db'),
  DATABASE_SSL_REJECT_UNAUTHORIZED: Joi.string()
    .valid('true', 'false')
    .default('true'),
  JWT_SECRET: Joi.string()
    .min(32)
    .when('NODE_ENV', {
      is: 'production',
      then: Joi.string().min(64),
    })
    .required(),
  JWT_EXPIRES_IN: Joi.string().default('15m'),
  JWT_ISSUER: Joi.string().default('mrh-academy-api'),
  JWT_AUDIENCE: Joi.string().default('mrh-academy-web'),
  COOKIE_SECURE: Joi.string().valid('true', 'false').optional(),
  PLATFORM_CURRENCY: Joi.string().length(3).default('usd'),
  REDIS_URL: Joi.string().default('redis://localhost:6379'),
  SWAGGER_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GOOGLE_CLIENT_ID: Joi.string().allow('').optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().allow('').optional(),
  GOOGLE_CALLBACK_URL: Joi.string().allow('').optional(),
  GOOGLE_SERVICE_ACCOUNT_EMAIL: Joi.string().allow('').optional(),
  GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: Joi.string().allow('').optional(),
  GOOGLE_CALENDAR_IMPERSONATE_EMAIL: Joi.string().allow('').optional(),
  CLOUDINARY_CLOUD_NAME: Joi.string().allow('').optional(),
  CLOUDINARY_API_KEY: Joi.string().allow('').optional(),
  CLOUDINARY_API_SECRET: Joi.string().allow('').optional(),
  STRIPE_SECRET_KEY: Joi.string().allow('').optional(),
  STRIPE_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  STRIPE_PUBLISHABLE_KEY: Joi.string().allow('').optional(),
  BUNNY_API_KEY: Joi.string().allow('').optional(),
  BUNNY_LIBRARY_ID: Joi.string().allow('').optional(),
  BUNNY_CDN_HOSTNAME: Joi.string().allow('').optional(),
  BUNNY_READONLY_API_KEY: Joi.string().allow('').optional(),
  BUNNY_TOKEN_AUTH_KEY: Joi.string().allow('').optional(),
  METERED_API_KEY: Joi.string().allow('').optional(),
  METERED_APP_NAME: Joi.string().allow('').optional(),
  GEMINI_API_KEY: Joi.string().allow('').optional(),
  SMTP_HOST: Joi.string().default('smtp.ethereal.email'),
  SMTP_PORT: Joi.number().default(587),
  SMTP_SECURE: Joi.string().valid('true', 'false').default('false'),
  SMTP_USER: Joi.string().allow('').optional(),
  SMTP_PASS: Joi.string().allow('').optional(),
  SMTP_FROM: Joi.string().default('no-reply@mrh-academy.example'),
  ADMIN_EMAILS: Joi.string().allow('').optional(),
  SUBADMIN_DEFAULT_PASSWORD: Joi.string().min(15).allow('').optional(),
  REFERRAL_SECRET: Joi.string().allow('').optional(),
  ARABIC_PDF_FONT_PATH: Joi.string().allow('').optional(),
  CONFIRM_VALIDATE: Joi.string().allow('').optional(),
  DEMO_SEED_PASSWORD: Joi.string().allow('').optional(),
});
